[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "clawdia"
path = "src/main.rs"

[dependencies]
runtime = { workspace = true }
advisor = { workspace = true }

rig-core = { workspace = true }
rmcp = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
serde_json.workspace = true
