//! Advisor — generates a Cedarling policy store (schema + policies + entities)
//! from a deployment's MCP tool catalog and agent role list using an LLM.

pub mod discovery;
pub mod generator;
pub mod llm;
pub mod prompts;
pub mod types;
pub mod validator;
pub mod writer;

pub use llm::{FakeLlmClient, LlmClient, RigClient};
pub use types::{AdvisorInput, AdvisorOutput, AgentSpec, Artifacts, DiscoveredTool};

use std::path::PathBuf;

use anyhow::Result;
use serde_json::json;

/// End-to-end advisor run. Caller supplies an LLM client (real or fake).
pub async fn run(
    client: &dyn LlmClient,
    input: AdvisorInput,
    output_dir: PathBuf,
) -> Result<AdvisorOutput> {
    let (schema_src, schema) = generator::generate_schema(client, &input.tools).await?;
    let policies = generator::generate_policies(
        client,
        &schema,
        &input.agents,
        &input.system_entity_id,
        &input.tools,
    )
    .await?;

    let agents_json = serde_json::to_string_pretty(
        &input
            .agents
            .iter()
            .map(|a| {
                json!({
                    "uid": { "type": "AgentPolicy::Agent", "id": a.name },
                    "attrs": { "agent_type": a.name },
                    "parents": []
                })
            })
            .collect::<Vec<_>>(),
    )?;

    let system_json = serde_json::to_string_pretty(&json!([{
        "uid": { "type": "AgentPolicy::System", "id": input.system_entity_id },
        "attrs": {},
        "parents": []
    }]))?;

    let metadata_json = serde_json::to_string_pretty(&json!({
        "cedar_version": "4.9.0",
        "policy_store": {
            "id": input.policy_store_id,
            "name": "Generated Agent Policies",
            "description": "Auto-generated by advisor",
            "version": "0.1.0"
        }
    }))?;

    let artifacts = Artifacts {
        schema: schema_src,
        policies,
        agents_json,
        system_json,
        metadata_json,
    };

    writer::write_artifacts(&output_dir, &artifacts)?;

    Ok(AdvisorOutput {
        output_dir,
        artifacts,
    })
}
